# GET http://localhost:4002/api/users

# GET http://localhost:4002/api/users/1

# POST http://localhost:4002/api/users
# Content-Type: application/json

# {
#     "name" : "Diego Garcia",
#     "email" : "dieggo02@gmail.com",
#     "password" : "abc123"
# }

# PUT http://localhost:4002/api/users/2
# Content-Type: application/json

# {
#     "name" : "Diego 02",
#     "email" : "dieggo02@gmail.com",
#     "password" : "lelele"
# }

# DELETE http://localhost:4002/api/users/1
# Content-Type: application/json